/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * sandbox
 * OpenAPI spec version: 0.1.0
 */
export interface RootGetIndexResponse {
  user_ids: string[];
}

export type rootGetIndexResponse = {
  data: RootGetIndexResponse;
  status: number;
  headers: Headers;
};

export const getRootGetIndexUrl = () => {
  return `/`;
};

export const rootGetIndex = async (
  options?: RequestInit
): Promise<rootGetIndexResponse> => {
  const res = await fetch(getRootGetIndexUrl(), {
    ...options,
    method: "GET",
  });
  const data = await res.json();

  return { status: res.status, data, headers: res.headers };
};
